name: Persist Progress Logs
description: Commit progress logs, falling back to artifact upload when pushes fail.
inputs:
  path:
    description: Newline-separated list of log files to persist.
    required: true
  commit-message:
    description: Commit message to use when pushing logs.
    default: chore: persist automation log
  artifact-label:
    description: Human-readable label used to build the artifact name when git push fails.
    default: progress-log
  retention-days:
    description: Artifact retention in days when fallback is required.
    default: '90'
  push-token:
    description: Optional token with contents:write scope used for git push (defaults to GITHUB_TOKEN).
    required: false
outputs:
  pushed:
    description: Whether the logs were committed and pushed successfully.
    value: ${{ steps.git_commit.outputs.pushed }}
  no_changes:
    description: Whether no new log changes were detected.
    value: ${{ steps.git_commit.outputs.no_changes }}
  artifact-name:
    description: Artifact name generated during fallback persistence.
    value: ${{ steps.artifact.outputs.artifact_name }}
  artifact-path:
    description: Artifact directory created during fallback persistence.
    value: ${{ steps.artifact.outputs.artifact_path }}
runs:
  using: composite
  steps:
    - name: Stage log files
      shell: bash
      env:
        LOG_PATHS: ${{ inputs.path }}
      run: |
        set -euo pipefail
        if [ -z "$LOG_PATHS" ]; then
          echo "No log paths provided" >&2
          exit 1
        fi
        IFS=$'\n'
        for file in $LOG_PATHS; do
          if [ -z "$file" ]; then
            continue
          fi
          if [ ! -e "$file" ]; then
            echo "Missing log file: $file" >&2
            exit 1
          fi
          git add "$file"
        done

    - name: Commit log files
      id: git_commit
      shell: bash
      continue-on-error: true
      env:
        COMMIT_MESSAGE: ${{ inputs.commit-message }}
        PUSH_TOKEN: ${{ inputs.push-token }}
        REPOSITORY: ${{ github.repository }}
        REF_NAME: ${{ github.ref_name }}
      run: |
        set -euo pipefail
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git config pull.rebase false
        echo "no_changes=false" >> "$GITHUB_OUTPUT"
        if git diff --cached --quiet; then
          echo "no_changes=true" >> "$GITHUB_OUTPUT"
          echo "pushed=false" >> "$GITHUB_OUTPUT"
          exit 0
        fi
        CURRENT_BRANCH="${REF_NAME}"
        if [ -z "$CURRENT_BRANCH" ] || [ "$CURRENT_BRANCH" = "HEAD" ]; then
          CURRENT_BRANCH=$(git branch --show-current 2>/dev/null || true)
        fi
        if [ -z "$CURRENT_BRANCH" ] || [ "$CURRENT_BRANCH" = "HEAD" ]; then
          CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || true)
        fi
        if [ -z "$CURRENT_BRANCH" ] || [ "$CURRENT_BRANCH" = "HEAD" ]; then
          CURRENT_BRANCH=$(git remote show origin 2>/dev/null | awk '/HEAD branch/ {print $NF}' || true)
        fi
        if [ -z "$CURRENT_BRANCH" ]; then
          CURRENT_BRANCH="main"
        fi
        if [ -n "${PUSH_TOKEN}" ]; then
          git remote set-url origin "https://x-access-token:${PUSH_TOKEN}@github.com/${REPOSITORY}.git"
        fi
        if git commit -m "$COMMIT_MESSAGE"; then
          if git push origin "HEAD:${CURRENT_BRANCH}"; then
            echo "pushed=true" >> "$GITHUB_OUTPUT"
            exit 0
          fi
        fi
        echo "pushed=false" >> "$GITHUB_OUTPUT"
        exit 1

    - name: Prepare fallback artifact
      if: steps.git_commit.outputs.pushed != 'true' && steps.git_commit.outputs.no_changes != 'true'
      id: artifact
      shell: bash
      env:
        LOG_PATHS: ${{ inputs.path }}
        LABEL: ${{ inputs.artifact-label }}
      run: |
        set -euo pipefail
        node scripts/logs/archive.mjs --files "$LOG_PATHS" --label "$LABEL" >> "$GITHUB_OUTPUT"

    - name: Upload fallback artifact
      if: steps.git_commit.outputs.pushed != 'true' && steps.git_commit.outputs.no_changes != 'true'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.artifact.outputs.artifact_name }}
        path: ${{ steps.artifact.outputs.artifact_path }}
        retention-days: ${{ inputs.retention-days }}

    - name: Summarize persistence outcome
      if: always()
      shell: bash
      env:
        PUSHED: ${{ steps.git_commit.outputs.pushed }}
        NO_CHANGES: ${{ steps.git_commit.outputs.no_changes }}
        ARTIFACT_NAME: ${{ steps.artifact.outputs.artifact_name }}
        ARTIFACT_PATH: ${{ steps.artifact.outputs.artifact_path }}
        RETENTION_DAYS: ${{ inputs.retention-days }}
        COMMIT_MESSAGE: ${{ inputs.commit-message }}
      run: |
        set -euo pipefail
        SUMMARY_PATH="${GITHUB_STEP_SUMMARY:-}"
        if [ "${NO_CHANGES}" = "true" ]; then
          MESSAGE="ℹ️ No new logs to persist."
          DETAIL="No staged changes detected."
        elif [ "${PUSHED}" = "true" ]; then
          MESSAGE="✅ Logs committed with message '${COMMIT_MESSAGE}'."
          DETAIL="Changes pushed to origin."
        else
          MESSAGE="⚠️ Logs archived as artifact '${ARTIFACT_NAME}' (retention ${RETENTION_DAYS} days)."
          DETAIL="Artifact path: ${ARTIFACT_PATH:-n/a}"
          echo "::notice::${MESSAGE}"
        fi
        echo "${MESSAGE}"
        if [ -n "$SUMMARY_PATH" ]; then
          {
            echo "### Log Persistence"
            echo ""
            echo "| Result | Details |"
            echo "| --- | --- |"
            echo "| ${MESSAGE} | ${DETAIL} |"
            if [ "${PUSHED}" != "true" ] && [ "${NO_CHANGES}" != "true" ]; then
              echo ""
              echo "- Artifact: \`${ARTIFACT_NAME:-n/a}\`"
              echo "- Retention: ${RETENTION_DAYS} days"
            fi
          } >> "$SUMMARY_PATH"
        fi
