-- Create event_logs and note_webhooks tables for LINE orchestration telemetry.

begin;

create table if not exists event_logs (
  id bigint generated by default as identity primary key,
  log_type text not null default 'line_reply',
  event_id text,
  user_hash text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists event_logs_event_id_idx on event_logs (event_id);
create index if not exists event_logs_user_hash_idx on event_logs (user_hash);
create index if not exists event_logs_log_type_created_idx on event_logs (log_type, created_at desc);

create table if not exists note_webhooks (
  id bigint generated by default as identity primary key,
  note_event_id text not null,
  event_type text not null,
  note_user_id text,
  user_hash text,
  payload jsonb not null default '{}'::jsonb,
  status text not null default 'pending',
  dedupe_key text,
  received_at timestamptz not null default now(),
  processed_at timestamptz,
  last_error text,
  metadata jsonb not null default '{}'::jsonb,
  constraint note_webhooks_event_unique unique (note_event_id)
);

create index if not exists note_webhooks_status_idx on note_webhooks (status);
create index if not exists note_webhooks_received_at_idx on note_webhooks (received_at desc);
create index if not exists note_webhooks_dedupe_idx on note_webhooks (dedupe_key);

commit;
